# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERCTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('target', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('product_id', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('paid_amount', models.IntegerField()),
                ('paid_currency', models.CharField(max_length=50)),
                ('topup_amount', models.IntegerField()),
                ('topup_currency', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('operator_name', models.CharField(max_length=100)),
                ('completed_in', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('api_transactionid', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_based', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
