# Generated by Django 2.0 on 2018-10-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0002_auto_20180911_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='erctransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
