# Generated by Django 3.0.8 on 2020-08-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erc', '0003_erctransaction_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erctransaction',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='erctransaction',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
