# Generated by Django 3.0 on 2020-09-18 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recharge', '0002_tempanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempanswer',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='temp_ans', to=settings.AUTH_USER_MODEL),
        ),
    ]
