# Generated by Django 2.0 on 2018-09-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0003_auto_20180906_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelfiveanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelfive_answer', to='recharge.LevelFiveQuestion'),
        ),
        migrations.AlterField(
            model_name='levelfouranswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelfour_answer', to='recharge.LevelFourQuestion'),
        ),
        migrations.AlterField(
            model_name='levelthreeanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelthree_answer', to='recharge.LevelThreeQuestion'),
        ),
        migrations.AlterField(
            model_name='leveltwoanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leveltwo_answer', to='recharge.LevelTwoQuestion'),
        ),
    ]
