# Generated by Django 3.0 on 2020-09-27 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0004_auto_20200921_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='NigeriaAnniversaryQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(default='', max_length=50)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question_detail', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='nigeria_anniversary_question_detail', to='recharge.QuestionDetail')),
            ],
        ),
        migrations.CreateModel(
            name='NigeriaAnniversaryAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nigeria_anniversary_answer', to='recharge.NigeriaAnniversaryQuestion')),
            ],
            options={
                'unique_together': {('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
            },
        ),
    ]
