# Generated by Django 3.0 on 2020-10-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0005_nigeriaanniversaryanswer_nigeriaanniversaryquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='highestscorestatistic',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
