# Generated by Django 2.0 on 2018-12-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0012_usercorrectanswer_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='highestscorestatistic',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
