# Generated by Django 2.0 on 2018-12-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0014_auto_20181203_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highestscorestatistic',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
