# Generated by Django 2.0 on 2019-03-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0017_auto_20190228_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaccountanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jbioanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jchemistryanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jcommerceanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jcrkanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jeconomicsanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jenganswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jgeoanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jgovanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jictanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jliteratureanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jmathanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jphysicsanswer',
            name='choice5',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='jaccountanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jbioanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jchemistryanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jcommerceanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jcrkanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jeconomicsanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jenganswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jgeoanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jgovanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jictanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jliteratureanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jmathanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
        migrations.AlterUniqueTogether(
            name='jphysicsanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4', 'choice5')},
        ),
    ]
