# Generated by Django 3.0.8 on 2020-08-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0019_auto_20190921_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.CharField(max_length=150)),
                ('question_name', models.CharField(max_length=100)),
                ('publish_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='akwaibomquestion',
            name='question_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='akwaibom_question_detail', to='recharge.QuestionDetail'),
        ),
        migrations.AddField(
            model_name='easyquestion',
            name='question_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='easy_question_detail', to='recharge.QuestionDetail'),
        ),
        migrations.AddField(
            model_name='hardquestion',
            name='question_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='hard_question_detail', to='recharge.QuestionDetail'),
        ),
        migrations.AddField(
            model_name='levelfivequestion',
            name='question_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='levelfive_question_detail', to='recharge.QuestionDetail'),
        ),
        migrations.AddField(
            model_name='levelfourquestion',
            name='question_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='levelfour_question_detail', to='recharge.QuestionDetail'),
        ),
        migrations.AddField(
            model_name='levelonequestion',
            name='question_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='levelone_question_detail', to='recharge.QuestionDetail'),
        ),
        migrations.AddField(
            model_name='levelthreequestion',
            name='question_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='levelthree_question_detail', to='recharge.QuestionDetail'),
        ),
        migrations.AddField(
            model_name='leveltwoquestion',
            name='question_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='leveltwo_question_detail', to='recharge.QuestionDetail'),
        ),
        migrations.AddField(
            model_name='mediumquestion',
            name='question_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='medium_question_detail', to='recharge.QuestionDetail'),
        ),
    ]
