# Generated by Django 3.0 on 2020-09-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0021_auto_20200830_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akwaibomquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='easyquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hardquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jaccountquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jbioquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jchemistryquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jcommercequestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jcrkquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jeconomicsquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jengquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jgeoquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jgovquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jictquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jliteraturequestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jmathquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jphysicsquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='levelfivequestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='levelfourquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='levelonequestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='levelthreequestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='leveltwoquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediumquestion',
            name='poster',
            field=models.CharField(default='', max_length=50),
        ),
    ]
