sudo: required
services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose up -d
  - docker-compose down

after_success:
  - docker build -t texplode/free-airtime  .
  - docker build -t texplode/trivial-celery  .
  - docker build -t texplode/trivia-nginx  ./nginx


# Login to Docker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# Take images and push them to dockerhub

  - docker push texplode/free-airtime
  - docker push texplode/trivial-celery
  - docker push texplode/trivia-nginx



deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: free-airtime
  env: Trivia
  bucket_name: free-airtime
  bucket_path: free-airtime
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY