version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t trivial-game:free-airtime  .
      - docker tag trivial-game:free-airtime $REPOSITORY_URL:free-airtime 

      - docker build -t trivial-game:trivial-celery  .
      - docker tag trivial-game:trivial-celery $REPOSITORY_URL:trivial-celery 

      - docker build -t trivial-game:trivial-nginx  ./nginx
      - docker tag trivial-game:trivial-nginx  $REPOSITORY_URL:trivial-nginx


  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URL:free-airtime
      - docker push $REPOSITORY_URL:trivial-celery
      - docker push $REPOSITORY_URL:trivial-nginx
      - echo Writing image definitions file...
     
      # - printf '[{"name":"e-learning-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
#       - cat imagedefinitions.json
artifacts:
  files:
    - 'TrivialArtifact'
  name: TrivialArtifact
  # discard-paths: "yes"

 

