version: '3'

services:

  db:
    restart: always
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - db_nw
  web_app:
    build:
      context: .
    command: /bin/sh -c "gunicorn quiz.wsgi:application --bind 0.0.0.0:8009"
    volumes:
      - .:/var/www/app/
    restart: always
    depends_on:
      - db
      - redis

    env_file: .env
    networks:
      - db_nw
      - web_nw
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./static:/var/www/app/static
      - ./media:/var/www/app/media
    ports:
      - "8009:80"
    depends_on:
      - web_app
    networks:
      - web_nw
  redis:
    image: 'redis:alpine'

  celery:
    build:
       context: .
    command: /bin/sh -c "celery -A quiz worker -l info"
    volumes:
      - .:/var/www/app/
    depends_on:
      - db
      - redis

  celery-beat:
    build:
       context: .
    command: /bin/sh -c "celery -A quiz beat -l info"
    volumes:
      - .:/var/www/app/
    depends_on:
      - db
      - redis
      - celery


  

volumes:
  db_data:


networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

