version: '3'

services:

  db:
    restart: always
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - db_nw
  web:
    build:
      context: .
    volumes:
      - .:/var/www/app/
      - ./staticfiles:/var/www/app/staticfiles
    tty: true
    stdin_open: true
    command: ./start.sh
    # restart: always
    depends_on:
      - db
      - redis

    env_file: .env
    networks:
      - db_nw
      - web_nw
      - redis_nw
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./staticfiles:/var/www/app/staticfiles
      - ./media:/var/www/app/media
    ports:
      - "8009:80"
    depends_on:
      - web
    networks:
      - web_nw
      
  redis:
    image: redis:alpine
    networks:
      - redis_nw

  

volumes:
  db_data:


networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
  redis_nw:
    driver: bridge

