# Generated by Django 2.0 on 2018-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180729_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='stat_member',
            field=models.BooleanField(default=False),
        ),
    ]
