# Generated by Django 2.0 on 2018-09-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0007_activeplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeplayer',
            name='player',
        ),
    ]
