# Generated by Django 2.0 on 2018-09-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0008_remove_activeplayer_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestLevelScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=13)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
