# Generated by Django 2.0 on 2018-09-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0009_highestlevelscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercorrectanswer',
            name='phone_number',
            field=models.CharField(default='', max_length=13),
        ),
    ]
