# Generated by Django 2.0 on 2018-11-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0010_usercorrectanswer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPointAirtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(default='', max_length=100)),
                ('list_numbers', models.TextField(default='')),
                ('bonus_points', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
