# Generated by Django 2.0 on 2018-11-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0011_bonuspointairtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercorrectanswer',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
