# Generated by Django 2.0 on 2018-12-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0013_auto_20181203_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highestscorestatistic',
            name='phone_number',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='phone_number',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
