# Generated by Django 2.0 on 2019-01-25 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recharge', '0015_auto_20181203_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='JAccountAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JAccountQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jact_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JBioAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JBioQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jbio_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JChemistryAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JChemistryQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jchm_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JCommerceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JCommerceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jcmm_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JCrkAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JCrkQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jcrk_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JEconomicsAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JEconomicsQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jeco_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JGeoAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JGeoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jgeo_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JGovAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JGovQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jgov_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JIctAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JIctQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jict_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JLiteratureAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JLiteratureQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jlit_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JPhysicsAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JPhysicsQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jphy_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jphysicsanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jphy_answer', to='recharge.JPhysicsQuestion'),
        ),
        migrations.AddField(
            model_name='jliteratureanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jlit_answer', to='recharge.JLiteratureQuestion'),
        ),
        migrations.AddField(
            model_name='jictanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jict_answer', to='recharge.JIctQuestion'),
        ),
        migrations.AddField(
            model_name='jgovanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jgov_answer', to='recharge.JGovQuestion'),
        ),
        migrations.AddField(
            model_name='jgeoanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jgeo_answer', to='recharge.JGeoQuestion'),
        ),
        migrations.AddField(
            model_name='jeconomicsanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeco_answer', to='recharge.JEconomicsQuestion'),
        ),
        migrations.AddField(
            model_name='jcrkanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jcrk_answer', to='recharge.JCrkQuestion'),
        ),
        migrations.AddField(
            model_name='jcommerceanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jcmm_answer', to='recharge.JCommerceQuestion'),
        ),
        migrations.AddField(
            model_name='jchemistryanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jchem_answer', to='recharge.JChemistryQuestion'),
        ),
        migrations.AddField(
            model_name='jbioanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jbio_answer', to='recharge.JBioQuestion'),
        ),
        migrations.AddField(
            model_name='jaccountanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jacct_answer', to='recharge.JAccountQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='jphysicsanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
        migrations.AlterUniqueTogether(
            name='jliteratureanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
        migrations.AlterUniqueTogether(
            name='jictanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
        migrations.AlterUniqueTogether(
            name='jgovanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
        migrations.AlterUniqueTogether(
            name='jgeoanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
        migrations.AlterUniqueTogether(
            name='jeconomicsanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
        migrations.AlterUniqueTogether(
            name='jcrkanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
        migrations.AlterUniqueTogether(
            name='jcommerceanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
        migrations.AlterUniqueTogether(
            name='jchemistryanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
        migrations.AlterUniqueTogether(
            name='jbioanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
        migrations.AlterUniqueTogether(
            name='jaccountanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
    ]
