# Generated by Django 2.0 on 2019-02-28 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recharge', '0016_auto_20190125_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='JEngAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JEngQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jeng_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JMathAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(max_length=500)),
                ('choice2', models.CharField(max_length=500)),
                ('choice3', models.CharField(max_length=500)),
                ('choice4', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JMathQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jmath_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jmathanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jmath_answer', to='recharge.JMathQuestion'),
        ),
        migrations.AddField(
            model_name='jenganswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeng_answer', to='recharge.JEngQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='jmathanswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
        migrations.AlterUniqueTogether(
            name='jenganswer',
            unique_together={('questions', 'choice1', 'choice2', 'choice3', 'choice4')},
        ),
    ]
