# Generated by Django 3.0.8 on 2020-08-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0020_auto_20200830_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiondetail',
            old_name='lecturer',
            new_name='poster',
        ),
    ]
